# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ec94b1ecd5b7d4a8d340d4e65d364e3dd951fcd502e7fec97d386f5df8b51332db0f69fa4923151be0cf59a71f1a84d99d9ce244bbf92fdb0ab54036ccc9700

test:
  secret_key_base: 77dbe6620c45165ac7d2bf1c826867ef6a10055933c19c00b406f48b9c88fc7390ad8a2ae9691214be145b782f089fdb5d42cfc65641d348e4e5a473e34effc1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
